site_name: CoFFEE for FEATS
repo_url: https://github.com/Dalma-Systems/coffee.git
site_description: FEATS CoFFEE Documentation
#docs_dir: docs
theme: readthedocs
nav:
  - Home: 'index.md'
  - 'User & Programmers Manual':
    - 'Architecture' : 'architecture.md'
    - 'API' : 'api.md'
  - 'Installation & Administration Manual': 
    - 'Installation Guide': 'installationguide.md'
    - 'Getting Started' : 'getting-started.md'
  - 'User Guide': 'usermanual.md'